apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netwatcher-2
  namespace: staging
spec:
  encryptedData:
    API_HOST: AgB9V5wL6bIV/ea1t7tWXiC/FQap2i+U+HC5WAnJFcZRE9NjuIydMNbkYecqsZ9Ug5qNqaQQE0iXlRpO8vwzInPj6WJLexGBLCjozHh91nUH0FaLfZKhw7LIVz3uhzHJowB9JD1/ehitOcypxvVkWZOi3TT34B/T4VM6X4b0Ta1GAMtrQjFG3jHn8fBrZyhw7bjHpuyhNFi/VT+WkQibl16tdFbdqIQYDQtWMLnXWls5woG9NpOk6g80CfdcLYximc12pP7lXFhVlcrs1BqbW9tr8FYDZCPBX/PF1T8msk9V2vEt2J6bl1uE48uywl0/NefEurmh67UfV/lW2Y9RaPfmzLX+sASUEtFIMmncAst56Mtr+xTVH9p5fLqEhvB6pMtysaBE9DPoeyQcmp7rTM4YoEn7TuKNcpbLgillknjmIQ8StwcF4IfeOM/SCk4f1hWX5861eRdSm9rn6YBq0nEHns8vUdMrYhiAxEfLwYbN4y+uhaoz881GMq21aAqS8n/x0dQacbMFJyE4xH3cu90lDAhnTD7/FVKArndcHdxr8DJ5arwB6EQZ8cY3lZRiuxNY0I/0MLSAOyczgJu3L7hfImpJkWaCzkReL9YnB+K2q4drSLsTHjqXeKsdmQQ+ECpauld7TjGxawjuK5jkd0oAPK7VRLH2S7QhuVhtpK24+ZyvWyIVZTmIlehCQsSFsTCpl3bX2+/k+pPrnZmDqZ9ONKoYM+n1OewV
    API_KEY: AgCQIVYIkeI/eanBM6qCfb3gl5HZXkHyWzTiZ7uvpH7NW6JIDpLe2lZUfE6BjklwfMoyFCc7PV3U2L3pXQqlTieb+Z+L5ILA/Mv3rAVvq0Cw0MtXFy5cnrmbxPJAa38LwsOJ3wPM0o59u9uyOQM2ihzcMjVANUpVHTiVPzWHUwM96/U4gUcHoKJQQ6LWHWKvBLKPJKiev3HEKwgMZ85Ad8RHixYptUO2imU91yoQo61Dxfyba0FV4fDrCytKJGg0BGpkbHVQ1yErIbWBDxk9iXxxbJKQ1KYIbGgadaehHk1wT/D267b5gIdLAsYUNTouMxDzYcwtef6HFxqM6VNGbDQm7JgmWgQBzMdzhgwfAYxrdJu0rmYt4Wmn+UBYXAC2Uz7hDwFcAZfdIVt4c4xg9NykmRH2sgUj6IFI+TydRfxfPD0FF5SW1nmiPemH6oP42EiGEJYSW6h/+GfzfrwJCQwdpkNlRCEDt4Phz34DXkXmi3iRtwRFoBh5pizkXdl17lM8nzNQ7waLlRjQl2x+xed1I8PqA7CR+X1JFrcqt1uoj8K+AuZ43LiuGSLahYxtb52QcGYAYA3gS7dEWKjEzU7YnkB8JeDB2vjkcv6sRGMfPIu6jN9by1SeaYrKzpuXwNMf8IO4NVJBc7Lvj8UpK8Dx4c4yLU9EUYaEh4I8K9yaPN9ULWbYM0C1q/d6UtO707WIfdzTleeJcmPfCy9QFFEFO5w5u/LNLvOjo0ydqC4=
  template:
    metadata:
      creationTimestamp: null
      name: netwatcher-2
      namespace: staging

