apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: economic-handler
  namespace: production
spec:
  project: production
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            app:
              name: economic-handler
            image:
              repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
              tag: "b2a624a"
            replicaCount: 1
            args: 
              - python
              - '-m'
              - economic_handler
            env:
              MOCK_MODE: '0'
              PGSSLCERT: "/etc/postgres/certs/tls.crt"
              PGSSLKEY: "/etc/postgres/certs/tls.key"
              PGSSLROOTCERT: "/etc/postgres/certs/ca.crt"
              PGSSLMODE: verify-ca
              TASK_NAME: fake_task
              PROJECT_NAME: ct-app
              MIN_DATABASE_ENTRIES: "150"
              PARAMETER_FILE: "parameters-production.json"
            envFrom:
              - secretRef:
                  name: postgres-credentials
              - secretRef:
                  name: rabbitmq-production
              - secretRef:
                  name: hopr-5
              - secretRef:
                  name: subgraph-dufour
              - secretRef:
                  name: rpch
            extraVolumeMounts:
              - name: postgres-certs
                mountPath: "/etc/postgres/certs"
            extraVolumes:
              - name: tmp-postgres-certs
                secret:
                  secretName: postgres-certs
              - name: postgres-certs
                emptyDir: {}
            extraInitContainers:
              - name: init
                image: busybox
                command:
                  - /bin/sh
                  - '-c'
                  - cp /tmp/tmp-certs/* /tmp/certs && chmod 0400 /tmp/certs/* && chown 1001:1001 /tmp/certs/*
                securityContext:
                  runAsNonRoot: false
                  runAsUser: 0
                volumeMounts:
                  - name: postgres-certs
                    mountPath: "/tmp/certs"
                  - name: tmp-postgres-certs
                    mountPath: "/tmp/tmp-certs"
            serviceAccount:
              annotations:
                iam.gke.io/gcp-service-account: ARGOCD_ENV_CLUSTER_NAME-ct-production@ARGOCD_ENV_GOOGLE_PROJECT.iam.gserviceaccount.com
            service:
              type: ClusterIP
              ports:
                http: 8080
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

