apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: economichandler
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
              tag: "6bfc6ae"
            replicaCount: 1
            args: 
              - python
              - '-m'
              - economic_handler
            env:
              API_HOST: ""
              API_KEY: ""
              RPCH_NODES: ""
              SUBGRAPH_URL: ""
              SC_ADDRESS: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
