apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: economichandler
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            app:
              name: economic-handler
            image:
              repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
              tag: "latest"
            replicaCount: 0
            args: 
              - python
              - '-m'
              - economic_handler
            env:
              API_HOST: <random_host>
              API_KEY: <random_key>
              RPCH_NODES: <random_rpch_endpoint>
              SUBGRAPH_URL: <random_subgraph_url>
              SC_ADDRESS: <random_sc_address>
              MOCK_MODE: 1
              PGSSLCERT: "/etc/postgres/certs/tls.crt"
              PGSSLKEY: "/etc/postgres/certs/tls.key"
              PGSSLROOTCERT: "/etc/postgres/certs/ca.crt"
              PGSSLMODE: verify-ca
            envFrom:
              - secretRef:
                  name: postgres-credentials
              - secretRef:
                  name: rabbitmq
            extraVolumeMounts:
              - name: postgres-certs
                mountPath: "/etc/postgres/certs"
            extraVolumes:
              - name: tmp-postgres-certs
                secret:
                  secretName: postgres-certs
              - name: postgres-certs
                emptyDir: {}
            extraInitContainers:
              - name: init
                image: busybox
                command:
                  - /bin/sh
                  - '-c'
                  - cp /tmp/tmp-certs/* /tmp/certs && chmod 0400 /tmp/certs/* && chown 1001:1001 /tmp/certs/*
                securityContext:
                  runAsNonRoot: false
                  runAsUser: 0
                volumeMounts:
                  - name: postgres-certs
                    mountPath: "/tmp/certs"
                  - name: tmp-postgres-certs
                    mountPath: "/tmp/tmp-certs"
            serviceAccount:
              annotations:
                iam.gke.io/gcp-service-account: ARGOCD_ENV_CLUSTER_NAME-ct@ARGOCD_ENV_GOOGLE_PROJECT.iam.gserviceaccount.com
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
