apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postman-feedback
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    helm:
      values: |
        app:
          name: postman-feedback
        image:
          repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
          tag: "591e2b9"
        replicaCount: 1
        args:
          - /bin/sh
          - -c
          - |
            celery -A postman_feedback.postman_feedback_task.app worker --concurrency=1 -n worker@%h -l info -E -Q feedback_queue
        env:
          PROJECT_NAME: ct-app
          PGSSLCERT: "/etc/postgres/certs/tls.crt"
          PGSSLKEY: "/etc/postgres/certs/tls.key"
          PGSSLROOTCERT: "/etc/postgres/certs/ca.crt"
          PGSSLMODE: verify-ca
        extraVolumeMounts:
          - name: postgres-certs
            mountPath: "/etc/postgres/certs"
        extraVolumes:
          - name: tmp-postgres-certs
            secret:
              secretName: postgres-certs
          - name: postgres-certs
            emptyDir: {}
        extraInitContainers:
          - name: init
            image: busybox
            command:
              - /bin/sh
              - '-c'
              - cp /tmp/tmp-certs/* /tmp/certs && chmod 0400 /tmp/certs/* && chown 1001:1001 /tmp/certs/*
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
            volumeMounts:
              - name: postgres-certs
                mountPath: "/tmp/certs"
              - name: tmp-postgres-certs
                mountPath: "/tmp/tmp-certs"
        envFrom:
          - secretRef:
              name: postgres-credentials
          - secretRef:
              name: rabbitmq
        service:
          type: ClusterIP
          ports:
            http: 8080
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      
