apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ct-app
  namespace: production
spec:
  groups:
    - name: rabbitmq
      rules:
        - alert: RabbitMQCriticalLoad
            annotations:
              description: >-
                Triggers when rabbitmq is used more than 90% in the passed 12h
              summary: RabbitMQ is overused
            expr: avg_over_time(avg_over_time((rabbitmq_queue_messages >bool 0)[8h:2m])[12h:2m]) * 100 > 90
            for: 10m
            labels:
              severity: critical
        - alert: RabbitMQHighLoad
          annotations:
            description: >-
              Triggers when rabbitmq is used more than 75% in the passed 12h
            summary: RabbitMQ is overused
          expr: avg_over_time(avg_over_time((rabbitmq_queue_messages >bool 0)[8h:2m])[12h:2m]) * 100 > 75
          for: 10m
          labels:
            severity: warning
    - name: subgraph
      rules:
        - alert: SubgraphNoEndpointAvailable
            annotations:
              description: >-
                No subgraph endpoint available (neither decentralized or backup) for 10m
              summary: No subgraph endpoint
            expr: sum(subgraph_in_use{namespace="production"}) == -1
            for: 10m
            labels:
              severity: critical
        - alert: SubgraphOnBackup
            annotations:
              description: >-
                Using backup subgraph endpoint
              summary: Subgraph using backup
            expr: sum(subgraph_in_use{namespace="production"}) == 1
            for: 10m
            labels:
              severity: warning
    - name: distribution-nodes
      rules:
        - alert: DistributionNodesNotAllUp
            annotations:
              description: >-
                Not all nodes handling message distribution are up.
              summary:
                Not all nodes up
            expr: sum(node_health{namespace="production"}) != count(node_health{namespace="production"})
            for: 10m
            labels:
              severity: warning
               

