---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: ctapp-staging
  namespace: rabbitmq
spec:
  importCredentialsSecret:
    name: rabbitmq
  rabbitmqClusterReference:
    name: rabbitmq-ha-cluster
