apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aggregator-trigger
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    helm:
      values: |
        app:
          name: aggregator-trigger
        image:
          repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
          tag: "1e28203"
          pullPolicy: Always
        replicaCount: 0
        args: 
          - python
          - '-m'
          - aggregator_trigger
        env:
          AGGREGATOR_URL: http://aggregator.staging:8080
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      
