apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netwatcher-3
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    helm:
      values: |
        app:
          name: netwatcher-3
        image:
          repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
          tag: "2716d5c"
        replicaCount: 1
        args:
          - python
          - '-m'
          - netwatcher
        env:
          AGG_POST: http://aggregator.staging:8080/aggregator/peers
          AGG_BALANCE: http://aggregator.staging:8080/aggregator/balances
          LAT_COUNT: 5
          MOCK_MODE: '0'
        envFrom:
          - secretRef:
              name: hopr-3
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
