apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-5
  namespace: staging
spec:
  encryptedData:
    API_HOST: AgAjqr/KnX1lfkt1ttN4dxoqySOE+GKonlifC312LOlQpntmJeO6wBYB24aHRvmaIGEtqcYjCWJReJMbDFolHi24Dej/v+HzpjwG83pxVFJJwl2+8OsIB83kJlR1yx9U3mkPiO4xGSSPPu6NYyOSahRgWj3AkHz6Ye4pDWNzs06yxZMGzW8Vane0Pkdf3SdvsBP9iHPomHEQXUbIFFM6pEixCaeFJVyimH5ZmaNd2tPDDHB2n6fnvgIqlYJmtvwGL0OxsSOzzgKyHiu346fm44hsJVTluO2SXy+79NZjFofLm+doD6iyJeIghXVfUT1gg/YwUnxHqzm0ERnl5PUSKGW5bjcaB+ZGDsMOlkJClEmHRBDPy0V5EWmwkpcfbp/BNS01JqrxTOzA1Tttdf8jinre4+L98IiTGpYhaYV2khK+efpfpPrJXZEi3DPBKjFB5LVBFKMIuJo9FYr/D90FS5E2H+mUshRIFxSHgJTF2Z0r5AI52AeulKYl/jS08cFvZ0w9HSmx8PSoqBZjijvNx/YknIUn2ZkIXN0Dc6EMHcZ0vDaNHSsHVKiUtd/IFahg9CHFE7YPbPgYiI9wZ2epMjiqbmm3Xo8PoXoCdyAW1i+26pZMabnbIWvyiCN0YAolQto4i/P2aYgqUSkQ6eEdTBPU+475qz8Zb/oeVXFRqFVdJfyNdabWWKGeqKfmRaAJ2iAanR4H7t67EMQ+w1PV78lxSGFiFuPd
    API_KEY: AgBr1PYqbmQjLv3xSyBaT7Q/BksCdW7aC3rwTgdn/p6BvPBJjAqeMbpSW87td2PO2p7ycIGFys/vB1LpvwoHywwu6c2X5KPHfGMACBGaJ29pMqC/FfawsUJTYhVaPXqKwMHfxp5L0m2OmOvCHS0qWgJautod5NFH803r0DoGbzwecF1Ml2nnH8B2u3YqKoBSul2OMnUbGiDhHHqzDWCcDXGl6wZfdF1xb79OECqtU/qTisVvLMyLNSzeCU74kO2H+razevGRNXVq2Gp08Z797sxCf5z0FjpCqxep+nEIqO0CAmyvLAV14qM00phX4FFPdYS6Ng/zCP8sACggimDYYA4eV7HG6Q7BBWZoP5mgCFUOcgvGtK7Yx28GtxhjVAln8lLFIIvGZVzzYbGj+xME6qPiaivboeZ6A+QktvkrATIWPP6PNqLhPjNcyupf2WCqCyGFdJZ7LD1HUi9xRayHI5BPJGmCLaTCnrzhHl34OmOq1UGMwag6l84RxAwn41nI6lT8xiQAKG4yKbrIk/fDJqqt1yjPush6PZoXhl8KRQH2uESuM/Z59a8QX+dniOtJKJDcyEPAf6UIsKxVxiktqoVlzq4AgrwGLHbLdMXt2ERQlUZbIDw6HylXI9/owgjWH5ILGLE6dYjcbZADhgznocnKex49X3pwaSxHqC5WA3J25IN06XzmkW8OSDd9IHQidF2q6kNBfOlY28mZaJ/H0iKT5G1NsTlpxEnaYy9Xyb8=
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-5
      namespace: staging

