apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-5
  namespace: staging
spec:
  encryptedData:
    API_HOST: AgClrgx6c8B0yydjL6kJ36PuMt0IPmofAkGn5NA/2u72j1EgWGtvOd0y4E+4i+xcm35i+lU9N5HxuoVq/EZdIQ9BbK6Ow5vTR9hCJsUpzIZMNc2nDO31JGxOiGazZ8v/QJmSEHJWPj2zULlBAly1Wg/bpDT8ymvvNK173Ac7pQfSI6bCvYw1iY3+o0xrY+dkjHEgzg8Y2FfanfXiQCLq6I9hHIMSFGnIS2Hvohp17NMMfH9Q3B9BQpjFMkJn+IyqjYyeGNiUOKdy/YjdXqsJjmIExC7r0mhKZ6A3i1vHw6oG4zxkpY7BcNXNoseRh1mNmJ5AnF+E7020ess/IQK8PbFonVv6mp6yGllqdYmgIAKdRrOXMZL+MRA4kjkm5wMIIPYiicHZmC02wk2JXx2TBlVuKgVjXDQL6IQ1XtLj1Ro8ir7EILOTfAsGOTYmNMnMI111G63UOLNQGAsO77eNey0urWGJwHwVqBuCVFjyMDbJCiZscFdZZDKvhoEl/IqH+l6uewjSsm75MYU+qpCw8aEjVm77T7ViJvYWux11Ix2CNaM/GAeM395E5mcAK0FEfYxCiB67v4Yx1bWBWIVk5EDBYoCZBqZ6Tw5wiNmwfxiVvIMkwfDp5SdTutYxpoikf6jfPHQBhljM++S6N0WJsq8xsCC9oP7W6EDU5UH5vQ7/sVwgsUpchM2TmNhQgbjMi2XM9JcqWL0HVHRf
    API_KEY: AgB7m7buEwYV0zmpjCugX7Flj75J6/HjJ6WqZQUmmfc5ISTjwuaKbW9QNghPpgniSXXYPqugvNwCjy+vLQtdJZ8e/NRxvZZHdgCIIy0kZ/r263sijaaS/bI9IcaAgMEfkpE8TokXft6kjj4I8AJALEE19w8VxFZ+qNImPl0txMoQnRXKvin56LxA3sxyVyrkKGXse22st9gze4WGFl13f8CbPbzx2bUgxTX0juVb7fVfKb8Pc5vsOQu/yKVCro5jVguTS+vL0Xv4ux1DelAVM9UVGG13UCXUEfh8SHNBD5SXq2eZwnMuJYvvsswdHRVORsCMp/YyYBJS/8F1HHVKIb0A6PU8rL7m35862KwkqjzEiGpE8HUfgcU7bdVx9n9GOEUKhxcWlseqTLL0MrXV6762m2IeI+ARkEiqIbig8kUTCZTgbCM0HLnYWGN2hOMrgAwBJd6sN43qoh9KUUUoHT2GSD5LmjsXjE7I8dRvOToRpraySEFbLw5gTQviLKm7qiZWzdlBJ3EG2wg0NXiB3BAE3jb1GTzwfN9CLp7vBVlG72S/djC5ZdiaKJBVzj9DLUsg13SUq5eG0I7TSl8ZvfiJLmzxOt33kRFsUWJCWwAlv2sjOJ3PL1lgFMz8vfMAeIAjUFX3EAoITGFXcQmmopj5p48aoVLLdyeogEkrc1pvXm+5tFzj/+Zep9VPyloPzDPKRrZYpWsyHXJQEuLYXmzr2PSRPeZmT3qZcTPMhkI=
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-5
      namespace: staging

