apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namtsop
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    helm:
      values: |
        app:
          name: namtsop
        image:
          repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
          tag: "4c923d0"
        replicaCount: 1
        args:
          - /bin/sh
          - -c
          - |
            celery -A namtsop.namtsop_tasks.app worker --concurrency=1 -n worker@%h -l info -E -Q "feedback"
        env:
          RABBITMQ_PROJECT_NAME: ct-app
        envFrom:
          - secretRef:
              name: rabbitmq-staging
        service:
          type: ClusterIP
          ports:
            http: 8080
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
