apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postman-1
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    helm:
      values: |
        app:
          name: postman-1
        image:
          repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
          tag: "e8df020"
        replicaCount: 1
        args:
          - /bin/sh
          - -c
          - |
            node_address=$(python -m postman 2>&1 | tail -n 1)
            echo $node_address
            celery -A postman.postman_tasks.app worker --concurrency=1 -n worker@%h -l info -E -Q $node_address
        env:
          PROJECT_NAME: ct-app
          TASK_NAME: send_1_hop_message
        envFrom:
          - secretRef:
              name: rabbitmq
          - secretRef:
              name: hopr-1
        service:
          type: ClusterIP
          ports:
            http: 8080
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
