apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: economichandler
  namespace: production
spec:
  project: production
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
              tag: "8d23178"
            replicaCount: 1
            args: 
              - python
              - '-m'
              - economic_handler
            env:
              API_HOST: ""
              API_KEY: ""
              RPCH_NODES: ""
              SUBGRAPH_URL: ""
              SC_ADDRESS: ""
              MOCK_MODE: True
              PGSSLCERT: "/etc/postgres/certs/tls.crt"
              PGSSLKEY: "/etc/postgres/certs/tls.key"
              PGSSLROOTCERT: "/etc/postgres/certs/ca.crt"
              PGSSLMODE: verify-ca
            envFrom:
              - secretRef:
                  name: postgres-credentials
            extraVolumeMounts:
              - name: postgres-certs
                readOnly: true
                mountPath: "/etc/postgres/certs"
            extraVolumes:
              - name: postgres-certs
                secret:
                  secretName: postgres-certs
            serviceAccount:
              annotations:
                iam.gke.io/gcp-service-account: ARGOCD_ENV_CLUSTER_NAME-ct@ARGOCD_ENV_GOOGLE_PROJECT.iam.gserviceaccount.com
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
