apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ct-core
  namespace: staging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: ct-core
  endpoints:
    - port: "http"
      interval: 30s
      path: /metrics