apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hopr-2
  namespace: staging
spec:
  encryptedData:
    API_HOST: AgAkMExFh0DOHj59WU8QB8EqQsV4KMR2FlhdpUx2HT3PIF/pjZ1j3J9Udh8zCpp3W/GOz2+mVKmCWRrdI0GVFDhy8f+aVuoksCvVCe7BN8CkmykEr92pk2vs+FXlWJ2BjsaBABlS0MXEQy6rjXq/R6TKVC8yVNEF1/r6e/DrK/PCUbccTCfBIABkOlFaKjoPRDHpswAqWXIKzl3UrDhBqL1hPd+Tno1W6yRCrcO/opPpCohQB1K6fbSVFLoN90w/esIZ5flkEVYicBK52gFvvOLZYWEiS/1j+zeFvg5ri90VEwl6t0xcgG9/pr5Lp7vRglOltZS7II0Bqm7c1gCou2aedQ4KrIom/0KAuKmFvuOZ13IndEs0cmkWtQvoxPIfQ0gY1XTB47idt7DH/8wJUZaFqEE74ZNz8t9RiFmV2R/JZOBk/e3Hv2ndh/JqbclkCwgXVbST07drEsK/4s9NliwkCME/QGmkUyL3TrcWPbX4fl2mniI8jKApFXTNZwgmgpQh6TifWy5C5rcckMslESuAfMREFQ514D/vaDNuZRN/H8bDVQ1uKI8Jd7KC605a+nVAdxrje3RzlUWHVt2uTnUSg5ht59nTsKwW2pCQg0lzdplsO/QN2P9Yf0+4nUB6gzffhDJUdZEJ8Ofxt0/aFIcHXX04nKYmnvY0Cba9b8NsC1YnFtAvefbCKTGrE2MUUcPo0Ojv8X31PHpSe5y5DEvnAtOS8fTWFxY=
    API_KEY: AgCqRxTLgJJXI8zx8AifZ3azDitjpnQalsRaSlBkXtDUN7DXsMvmiP2g2I1ru1nI3yaS31xggGNbpRAf4S5yVbilIsRs7l9r/luM4KFSDd2mApqcAEmBqpM8Vm9cZ04FYvPzwZWIj6ZnOOut7wR+KE992m2nZxiORiVu6G6eALbiz9epSkTrANKbTs8Skk8dBDSQGkCl2XSc0W7tQayvIDIlxUrLs4iYH+92YV6Irxn4CRSpVpTq0qXihgPmaG8MdfuNIPBaCFmJvGI4oT3iJst/6ZgfpXzV6Y7qBM6/oTWKRklhFSMAHgZ5Xsy5zrZ5mjMoWJcpqAk30Bnm4O/pRJvGaFDkKh8jnaS9eG52nCHlf+ILuf1O8aQwAQ8lYBygJPfeTQuqqcnrsULCOcVWk37Jp7vilSOz1LW35wx6Wr6MYWqW/vVpGF+jO5vKVPGAL48o+fmcgOH+5pG6dwzwy9Yj6+VFcDcxuO2OXC9sTin/tzdP9H7UQvXm8OcR0YNt4kYC9prGdsEx9ZcXtDIIPkmT0+eTRoxs/8bUhM30CD8CH3Yxvk6W+ezihzLbevSiy/podI2dAvyfCM7haAyTurBJ/HnCFGYREggtFPpjYCjbk6LWGff0/HKqeDKwYqzE9yKH5A9rMGfAQ5Qdg8k6o5IodE3EL1JxBf7rMAwOqG+nQEv9ufnZ8bs72d4H6+s0uuVYFsFEUWQZc/LYIPvYh8exV9OhWUENyvfNsefVcKs=
  template:
    metadata:
      creationTimestamp: null
      name: hopr-2
      namespace: staging

