apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hopr-5
  namespace: staging
spec:
  encryptedData:
    API_HOST: AgCLDicFBGHwV6i9xuBenBKBHb6zdwp2S03i2WQXSIfr9Qh6O68ipUSmNVKu1iMGd8bBLe5N/bsEo5AFY5XkttVTAyFBXEb6T8CnnAhDSeZ/Lcxm4tGCEz6ofOVg683AFGWBYK7IyORTFtoxfFVUAkCEhpuwTYW5w46aX3JCaqC0e6CtOuO3BzmA/xWScu+GBqMJSwDJbAhx32FOlre/YWBswK+CbX7ucofMPRXn/ekfqwvlEk9oNockZGdmMmNtWCsHhZZu1qmJT+6VLA9Fw5Du1W/7VzW57iVy55x1Gn4yvxoW+jZOyvbdRLfhR5PhoSIgL9JHlhyVCwzW+/ZV0/Wiwv4US2HRfVwnHY4SGMuXxIoZIPcq4g91fln+j9FFCeJ7VadrAwH6IvYSPfJBCoAXtqRtP3dUcy3EdtM03hu2vIk4BV9CF7YJ/2LZV/Zt/GpoLeGRgpWvJDGV9eu8tlkROlzde6KHCGpqtAGC8kyB/1nXSoBnm27jIKrfKAE87NItbWOc1sXbh22ytjyc+rFSyXBMQ3leRaUZRK/DVanpI2IlgCn2xH7mgtytnyRlXfTC2Fbk5WIbe2J0/yoDrMxwZt1PUuYZPUXFRiyrJxg89cMNmOZiHeINyxJISWRZ3PijDrpv4NRwubkuvPv+WgdD7DnAKQVOn/3KR7qX//6nTOL72GGF/mI12dXI/+cDtCK8YngFU35DRr9ZP45TuUrD+cQWHltaBD0=
    API_KEY: AgBrs7UpSWdHlvYUjBIhs7YZyhc+Yr1K/b6uV6QlGG4XJnkS64RTdVoqlB578CSxnGK9uT/zHIhgrfDmFSeQLbbzNDZCE/JBb2XVwjSNr9JXHZGTcwXMhXVo6M/X7PvdluOl5QcbS37yC1dgwi/TvqZ59dF2fsB5T+bcyr2gj7aDVO5cQ/vBjwRc1q78t+ciF92t3ZlekdYyiIYrbgL0IB5+f9hp7OwAEWeB904kiwXufLb/fr0e9Uo9QeJYqa5sJ7PkM6vKK/nTKCCj1pB414OU7nmgr5d4dDTBH9eQovM8yJoR1TCNbcUiAVieQPliFxjyHXcQscUGW7gYa191InJq5i/LDntJ9OsAkxQ5qqrsRzIP3gZ15b3na/QImMLhPJYVWrRQblWWUIG1uh/AMvbqWG8cc2VTm8WY5gocqw19u+xc+wYOsAPIl75azrsJUYdliWFAPAWcSc2IcFYZtsELBxThdpGoB8OjYRUcpX3femQSfteTUBOwzyH0mI6Wq55BC0bleAfKLG493N5lZNIpetfFKVhEPTOkNmAsuZSEtNJHcKh0L/zNroFigfFqH183NNHzhCuqsk7W1XbtQ79UzpaU17g2uEOeYCBubKImR9bAKSJa2ZwZXTejN6i18nTzBEKvgXmf8dmbIkc930yYoo/UEe9HdwB1veO9gT7o+CqwmaIdyyHxWDAOZJMpmoKRpWax6SbaczPDR41RgLGhbYdQah85l3is7yM3Jeo=
  template:
    metadata:
      creationTimestamp: null
      name: hopr-5
      namespace: staging

