apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hopr-5
  namespace: staging
spec:
  encryptedData:
    API_HOST: AgBzisngzb4hmxnG5oDP0Oy8/iclJrdj6fn8SfgMd6KshJFiWfJsfCbIWyBMfwYm5pINOgPxVNDpTo63c4YRYTO0JGIRzKKjNQMnjK0NDmgdvTcjQi2yByNfxdMFXDZ8suNb5Ss+bhJ7dXrYvgPVwKX0S6TCA1JO/oobo4NJHnprIjqh+dfUkqIUCB8sDSRHHYCiQEEGa/wX6fx2gIoB8X2K2xU0EJWPRD7ThfVHQ42zOGpb7iZYHNzKlYoTKJb5vp/dxdxAprOLlm6QwITfRPLhvXAEeaz13mYM1RGPLdH6EBsOCCreAkYp2niRfe3WQCDISmKMbBWf3SX9BCcLcntHpxi2o+qaLpBDsqlQTLAWExLPy4jdKqIGk3VVEsyOcHCClUHbEsng9rY0hpugQUCJZRYtrT7s9Mo5RZCfV8SPROZLiWt6zTSY5npCwP6GGqq5QQJzmQZ4zw1ImMWiDX/Zv+roeuYqJGodCg31pNs4XG49Edi+BDmbhLbUyvin4zzMaFQWtKSZO7pmmuUGrPxNpPr/qGOuKCvaP/EmRX6jbcI4bvoLecOr/zD2F4ht6DXI3j6azQVicdEErhqNE1zBDHduQ88AqS9hRmmgMnbeXYUQPOI955pKLoy943eND7ZhP+crqTQxbQdkUCqOzgLqt3s5pNGwMLkjELQKtqaxl2qXPov+g5plPLToqQRMgwF8pZ873yCvgQlOkQaUakb23sXcxLZOBw==
    API_KEY: AgBVyY0aCcn2PFPQxa37kFTQh3fDtqbPrfaMjPdWx2CrK2PPT8+YMAJXfNyRwrQ2wl5EWLJMQIw+I4tt5I4KQtlCrk3c6MHDyHG0T+IAVIxpna22nie0rZ0X0dCu4iSZUv9Yj7lQKShBPrptDzWprZ80aH9X1O4IHlHENrzOZnjmGcYzJNFKCdk5+qgz5uaL1od+ZZU9wMXBDlmztSwKwawakyV9jIyheHtgWDcxEfJCL+3C0keV+c427mLrZLjwP8T3fvDQqjCDFFV4mv5BvBtysoxieK7RTZHvxcd6RI/wPwHWYJSB2m+KOcqyUMKmM4HsvA14dBa6r7ZFQ+i17xXVm0yZd0DxHntoywX42qIqc9fNrgFIdSUHT3EhAS/eZ+5PJGDtT75U4M90pU8dqCJ8zdDColVdj2VKxDljlGFd9sxbJcn9GHZ6JRlBZ04fAZd/weOfkMDsipQZ3lho2hd0boKxsVWKyTZyUAUBl+CI2P7KHjDZ6IVJKShbiBaoCjoNN7STVvAQ0sqpuLLrFzlnv4cq2tkHL8BvMRArlI9BhI7HYQUt61j7hXVQgwvi285RChaqWkO8i7nNzp3utDiAouAO/xaeL2gHN02yTv+HyR+X0SAOIs7kuaLiX3zP8gZ9jluJO+Y51SK2pMVgTlSLHxXvNdxb3qJ4SfuDYZRJH5Niz0P8b5N0wKUmzC4xf6NvVCdHqa5HXPgZbJYsyAgOJLUEHVIOf3JPK7TDf7k=
  template:
    metadata:
      creationTimestamp: null
      name: hopr-5
      namespace: staging

