apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hopr-2
  namespace: staging
spec:
  encryptedData:
    API_HOST: AgCowFQMg3o9MaLzdZlCoCQBarrTUiPyzngtsvK21a3TEJrP5JXIdnBKAyrdyjS8hXuB6GRf2N6MA5qjajRUuSu4Mv4KNMkCeJl9KPYyeqmfs6jkNMiKeuNcbvMVDj+l1yh5rpSVk6v/ExL2mO9Yi+8kmPb+rT/CYddDo2EpzW7Q2bHLJVdeYFWb8LXW9HUHCv4KLXILxXfLC0zRGYeld0CaKFji+LKQg4hoFCk1fFwcfwMUGAwoUsCMI4bx2gZH9bOICcPDiJ8uu8YS2aWh7IxHWYvZ0G60Bfc/+BA0hbHY0n6ZwwIP5ReNMzXxCyq0M/4zf//wbh9oMR4ym772J/1DLjs8CMPJKi1ZDx9uVHcTf1j8u1Buwr36yJQFblL7LVhOaM2bPl1TS9UFqZVgCBNJeXRIwTUrky/gAVUEBBhWBldDM/r3nB8tRJ8hhCcn9kRb2+B/3b5OdHcORt6JZmvryzkUmVUDSAMUCTpIW9Akdtobzf4YPSE1Hl4fH1BUxXq4TW+ecdheqhiN8ipttIUFO30L2h9mqKU+SMQWRbmD1H+17jC8tAxXKSeQZ7iTSVk3+cnUVJDB1kLC4UzzfnECjcTeTTdUQx7xTmAtZ3cnWuHVhQHtjRB5acYvWt+T/qvBm5z61o+MT3zhK2S+8jxY0gDmGJuAqc+T+sXrE4cBFBSouxWpI1yGv/5re7cHk8Xyx+UYQZ5ffcGlkpr2vq1Y0DGQZizca4QF
    API_KEY: AgC1XuxRzVchEN9B1WFkn8pw//eA3TH7NMHPPZuYmoC7gHvYhNYruBwPTk6aJcmJrWIAirvdRdvDrzoGTvuRIlvt093mhR6OUqoUbe6MQqcGpqB0iDgYE77An7Sgao+c5onhfwOdvbPAgWwdJpBy9d8N20s/+2QlM7QZZAiLC2TM1EStNHdp66+uUkSqiZRH8U5ioQ9VpeVbFWDe+rqsB7WTa448KsvVhGB3UGhRlvgOlZT0nWdWPmcUJF+wRrzLAHcUcmrmYzBsX5IH2So7sHgQ/d2idhCvS+kpR/OnTwF2nTa74cwB32EaOL/kC0uZXyrnhbkJxuOi7TfYeyIMU0J1SuEUm4G+J62YYOFhprcjpZYizpm4ZG251FIfbiyP7nvuDsxhg03SECL/gVq8d0ueI9HbCc9AMVh7QBe7O06jDC6ejZV6OF0rryjDaDqGeQumx6fKmrZbK9c6ZMW/C5bQFjSkvTlWkg03q2OJfzUujnq2SiVdUpf2tdevqpLSkdnwtW0ZsTb1X28C/dO7YOpEgROQ5APD6Py26EqSRbw6qvKgX/B9J60716VFNFbPVqUpJIsMye9CM36rirrJCHJMixWMFhuiorjwQHp2UseFiMJy69C2kKp7ZkAF6KctajnL0oPzOxafn5FZT4F+tNTq0qZy2V7liWf3aVLg5eeR4ipA/GAmyTeLlVDf0sYqoO58A1zPA812ucfvdbr9M5HxU8qCH/sU5H0sqr5FN4Y=
  template:
    metadata:
      creationTimestamp: null
      name: hopr-2
      namespace: staging

