apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hopr-2
  namespace: staging
spec:
  encryptedData:
    API_HOST: AgBFJTKa1u0PLK33a0PepLsiwRNIMrhAXGd0+0tgOOGoWBzxnMe87S9RzWUcgTtO5IUcntdlHlGQWBQd+8DFbe6FAzBR5T7vK4pDaMHx8R8hac5Uzugfjs0K+aMocF1SDxamoqjmHnYJaSV/iXeNZ835kNGAB3DtKhi6/ilTfeox96J5i/T69UbXyAhzOck3tDikAaJK0fpXB0zdQOfa4pOs6QnPDqrhp5uYMKhF0vAdhW3tXbP2Pe+HL0095s7vtntatFD48xZcydszuR0Uwi3WU10pW8HSq5qFWPhWHiZy6age7wD42FmtRlyyJ7WURJv3lHiBFEhPKjOHg/tLqeRuYjDd6vQ9oNlvfm0FUJhp+aOKfWrX1yfSydvsu/Bn3hNBrvyfewPy75E+KK+WWYRKdNAtU0bUGngKb0sZ21AiRoegfyYkjGsxnohOh9KktaxhPcGZl6/js1NpK5xnyhEK6hTvqW3p6VlYr7xu6SqMabXjlaLIo2Z+zxiR7Z9gYyeFciBsqa5qU5ai4eELm7UTGPAyDT73/YH7+Fvp0ZsXpK1C2l75RAgtC1oDZjO7V/2D1p2NBTMMc6Jxgmwlfu3h4xC7rUxp21R/pejpR7R3GnG47L/qEGXmv4wnGMMsZfwTPwKUVw1B93mmT+ZrPBXCnb9eg1Kgbrt6NSK4gQJZkfTSpd9RCYATtl8auckDnJ74JxES2DHZShoRdYdxq9HuZ7yoSp9CAnSf
    API_KEY: AgBSdmvsM1ADsFVn1RG4bAXkbYFVactgswcLFr+kRSaxdH2wgImgBSaGQDS7dO1SPHXPOXoyXGAkikPIAgTz1R58rdUK6xtEGEXCVOKz7wsT+9jet7TlwHoNwsgeCNwS1h6vriJkRDHWpwxzJf2NOmGD7AleL8rlCL9BINIRWQPaXCzRcNEbZRzChXHMmhDaJxeol7nO/D2GHnCbyc8iUlu3akUCdc9qqAE8ENvbzB71mB1GN+rNpylyRsQC5sOKu/n1M8QsqgB1zbyLa7O1z74q9ULJO1kr9odeNntSlfiplVXO3vv9G9ErXMQR9UWuduQSMpbhgob7JTA/vFV0lMfRw6aVenr4oTyyvIFfgDiptGjqf6ipjpbNkBlpDxSjtRjTvtvlHqPcK1GEePVzT7TPQhjWghV/CA7/Jm/xjFAaAqSLQ21B7ABNYf+M+wrjPxLUf4bWLDhC4RwS7Nk8otNttPHB/v8K9BVzdWAuMYF1tdrNf0lWlQunyswBXEAskKdySLagbE9N9BHSG6uBvbJ0+tlHl367RO5gS5Fgpl0wsT0nfAuGOUxUj5Cb0E7iu+qrICuAxIRS5VayGmjXE4KWlkd4/0VCAY7u6EuZ/a1QS3yLnNY7syja4pUjAGgdnFW3bj5M9ZHHvuKEAvl3MCUKBjYFbAlexFsyocNjt8bhTiHnm1BOvtr79WNOpF1FfwLcz22z3pNQJ1DQ/4hV/sjLLSCr7t3kXYMBkkp8pz0=
  template:
    metadata:
      creationTimestamp: null
      name: hopr-2
      namespace: staging

