apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: subgraph
  namespace: staging
spec:
  encryptedData:
    SUBGRAPH_URL: AgCB8k/+lvh7ZorzdjCu8GjDVQyePFkuiNb6+6264n4hXUNXmDzVbkHS1+qCfXEJhGdTgOPdDq5kLCkFrYGcUwqemLzQ0zQYjij65WShLbxZHWvc27TN4yRTSH8vsmJWI52UZWXyyKJI6LNpbTOpXCKoHvjaeXm+pTNU6NrHp5pd7zXm8253aTNMEXN0A9SnlK096mLVmNPptkoO3uHD22PZmFQdUsrZy/47TIzeMHOgtDAwEgnqZamFw0iPuP2MFrUIsbZgeeegPJsPHqUi7KhAUp37PxLGgCYh6QeVXR1qH+3rZVJxYa01geeYnMJHEl511ayB4QF6RMuC1584kEKApZ0t0qxhx/09rn2Qv7+IPTsWGItJezDe19YecQpMwD8+N6Fn0hWgxzQucMBvYDJIoWe74Mcd4Fnzi90Aib8zWGWtx0oA6TVmA0uSl8q75fEXRQ7oOKcbuOfdIh+iWaJLENNPx8yjj/g5QunemvbjXmHw1gNGnGwLlRApm48cjBNR8E2ohGU9XJYXXc4nWLpuq9eRTs2c3cz1gmZOisUjwxY9eYY602p12xdjyWz2PppX9LXD3UXn6pccp9YSaTkYN4DOcP6k1UVrJG90lDi4SjYv1j1TTZUThfEKaggNnjaMe3jo+xWXxuDxcsDQ4d9E3JvRWf4MG2k9x2MyU7SHo5SmtoTYri6N1ldHiD0nbJAPGFHJ/m5vc/ri3bhkIHwGapP4VYzyXDimZXAvbjwvwT0bwCWliL2aIXWy5HOgO447nt/Ar2jF6nbMamkGwNB0D+XBwOKZXpGclGR+wixLH8pCU/RusuoWaqQu/TpPKWlCdXtnSU+P+1FV52QWTaUxbQFYmvNHyqoHUi4=
  template:
    metadata:
      creationTimestamp: null
      name: subgraph
      namespace: staging

