apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: subgraph
  namespace: staging
spec:
  encryptedData:
    SUBGRAPH_URL: AgCWVLzGRgnC3bUqbq/sg3CRGaA7dk19UF2sfHk7FcHqCK4Q8PX52T47iteFmEg1dNT9OmX9hfoILzM/Zo6zfvuu+dI9I+3bZuGflQWfYcBXnklwV6TYbhEYq1v9zLIwgc+lbn+ha/66IoaAzi+8g9A2oqFUCJgssDZefT/eMxRgTdL9APQLHQkx7fEkiWLwD09LhVj+IukweHSuxStnpQXdaWzHdQgX3q6cVc+XyswHZMCJZOTdx4jQikSYPjVgFi1pa+Age7T36MAj50LZgL93mn8XvnbM1zcnxZ06k+HZmo/OVR1BYeg/i1t+CX6cypdB7lByk2FafmYgNELP9fu0WPbUZq8MII/fznvL8TuHWAbQnx2w5zO0Bv024L/cR1kJmGQ17wJVTk21MmGBvk0kotS1nKAuQXQdegej1BIVHA+rLktLi2+tg4NqCNpY3qipRg3EUte6YHqKOVrRbIIpyC5VuJ4eyuzxuGvmZXlD3GcFmbZyXumey62eq0ow/THPTSyE97/sHFOn6RaDORu1PHhkeIaXBcRvMo4/6LpkDV90gnQy7mRhogBhq1M3dSACT+IZ9KGScfX/H8GYJWJ3yKH0yXnOOvwjByNasVv1sYdz2R774isy1LgjO9FGfgdAl1y6Z+KR2cN1ZdmG3HjWuuLsXMX1QPqDunJHj7Yf3IZewviVDj70bpwYpb5GZBbfbMGFb6QKK31Ha44UHny++SmhG/EJl50+JlfI016HzJ1m0K9HO2tSqQaXq6FLczMrSS/ONicdWRs+ubpw1QX5UfLBiJB48iKfMhWIN2vTE76F4ZJLOBl2dSFqMObPTow3jNkK1687HdKHym5kMDN6bnbLkKQqTDyCpsA=
    SUBGRAPH_URL_BACKUP: AgBzSafIMbSvF9qrmuO2g0LMX9YVAyAbkPZlNj4SzFXCYR3lWTqnzaRqmMu4GcqaiUDF+zp6w34JD8QeZaTSiDX1gMzdIPBs5KbQZDTwauW589Pwo3MuEgrzKNxfd5TKyvx7dI6Jptno1NhCZS+KNwNCt6ymFGfeiMx1i3gEYl3j14C19mQFqKEvLATCLgJ+P0dPbM1gALXn+t1awbEwPHpbszMXRXKVy57LCklSnUp8ReBqrCgE+kah3+bDyY7Y3lJL2qzSNaXGYTGO4yqpywSzoRi3NC8kaDb+IGDVgOcAx+fguLxYvkqwaQ2XaYrpINmQ728DiAQ+MJcVxTSSrsg0zudA1wOZkes0Y1WJnrwdtrHwEo5kR7MaPsLb1WRcFBBQlWkOXhh84YDrIkIu1xCIclFAXxBGHQf4A9j2t4cC25hlhcxhMTxO7zuiYvMTSwVVioX7KpUw1FcMbvByEGHGASE5Gn5OF13JAabvdiDg9q2CTcFmZJCCe+SZbMhF5fN1Ir9lOPbzFqdUQigYsPHSzLt9+cOteConyN4JCuQ5baf4gTZ5Dp6tfSONSDaeupi0jPFSSOkRz7kokWH9ju2iXqBt/z5sJhAbxWBpx85j2tti7E3O8lvepsayDl92QnHYArgGmsfMx7+R5l0s5SxDLOMyFUbv53LCVHuTBWqyFuOX0JfCLj0G9QqcfQobcxz21bpVYW7WMeCoPFV2eXtW2e/jA2BSGn65DTqI7JxUPNN+2+CccjynxAr8So9Bcra+IYTnFzy/Mk5ZwcT6q0tsWomVAdENJl2s8B2m
  template:
    metadata:
      creationTimestamp: null
      name: subgraph
      namespace: staging

