apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aggregator
  namespace: production
spec:
  project: production
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
              tag: "d06f325"
            replicaCount: 1
            args:
              - python
              - -m
              - aggregator
            env:
              API_HOST: 0.0.0.0
              API_PORT: 8080
              DB_NAME: postgres
            envFrom:
              - secretRef:
                  name: aggregator
            service:
              type: ClusterIP
              ports:
                http: 8080
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
