apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aggregator
  namespace: production
spec:
  project: production
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    helm:
      values: |
        image:
          repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
          tag: "2a8d28b"
        replicaCount: 1
        args:
          - python
          - '-m'
          - aggregator
        env:
          API_HOST: 0.0.0.0
          API_PORT: 8080
          PGSSLCERT: "/etc/postgres/certs/tls.crt"
          PGSSLKEY: "/etc/postgres/certs/tls.key"
          PGSSLROOTCERT: "/etc/postgres/certs/ca.crt"
          PGSSLMODE: verify-ca
        envFrom:
          - secretRef:
              name: postgres-credentials
        extraVolumeMounts:
          - name: postgres-certs
            readOnly: true
            mountPath: "/etc/postgres/certs"
        extraVolumes:
          - name: postgres-certs
            secret:
              secretName: postgres-certs
        service:
          type: ClusterIP
          ports:
            http: 8080
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
