apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aggregator
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: production-aggregator
  endpoints:
    - port: "http"
      interval: 30s
      path: /aggregator/metrics