apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aggregator
  namespace: staging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: aggregator
  endpoints:
    - port: "http"
      interval: 30s
      path: /aggregator/metrics