apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hopr-3
  namespace: production
spec:
  encryptedData:
    API_HOST: AgBz/WVQwbtkBRT90sT+vAk7HKjgVyKiJ93FBDYA6NgtK450+CkqPC81CKshL6YlQk7ii/oC/w+6rekzGiuWRagzD8QWlCSv9dtj52waq2tWZGvO/eiOuGMe1pp2FRZbhUJHiSLPxRwxgTa06KuuqI+prCoaEsSkO0Tj0IRJm6SEnYgTUbnvZxF67/fAUUbRs7HQSIXOzkEi02iYuFWfOMa+eLkLfjx3wcnM7q0hH6AzclmZ5vwEsULi7mRZma/CeyLZqJgbwBvLOEH1SOyl5VeSrkNns+F+CxlWip33fhr3JlBCjloP0jNofsqAvi0PIfnnYf4OAjwbRPWwBAO5AiF1H1+6OPrhwpCWHggcI0XAxIKKQAFc+YblF7kXxpXVyyIcMRqwkoFsJJ/L6kJW3g38fGDulEda6STHh0Y9Mk/wNfm4Sh4ZZNqfSWW2tHOHBd2yVvUAQdqjvYakqWLQEIS9735ELtgFycvtJpoJVZlGwYZ0XqKkiPse72ntVA733YTZGzb5ypn3LzYWtSzgo8bilPuNKbKftnpn2sjOxi7ed5CxWStWo4n0PkbEpWHiI+DLEYAaAp43xsfOGXDwhTqFAFnQ62zYOyr7VsBfEpc42r7HzzocCOIdia4oL8uSlw5/vmEq/DjN87uR8AiSNI4DTNIFrAoDMUw0bz+pUEXrfAnd6MhxnMXe2jD4cIBn7+4C3tOMShrqA2i7U1WoKgr3t6NB88AZvA==
    API_KEY: AgAulJ+iqYwGV2h/AqchmDyCpKD4d1UkVrYeecnWwIcSxZx1W51wK2zV7L0vVYx2J65QTc3sZb9wGuAC26yyeKYMyvcE+o9GQ1tlHK83dM5tMmc1bOMAA+lsIpFguVEFWfX6eDGAOtAynu/oS41Lkk9raht2JfK6eAtzN0iTGNufQCLmS4cCgo5JCGQGAYVeKxmEzw16F1jubp0MZ6iTFKmr8VDN8PGBNbZDNX476Fbvz7n8AoaaQyziq1OoWm6cMVniuL2FzFjPC0VcuIZGtZBhvpeMJEQz8OIi5Wi7cBSEsjx8Bx+j4ycKRqmIMzDliPYHyhzQ7/TTRWjyMDELOPwlUN6tpy3iQci6EsUZLLdg7hndZnTxuYsZD5pBGDdWx4g2IWI+aAGCNoNqKNWQRFj5ifkkbZ+602y/bzT0YvGw2G71WFok+vBl22nA79TC2uJHc0/eWoBTvFaJlLPQ5wpcmlBIDPxsSdwp0TAFjInMILG/cqHHxDI639HMrH6Oz/ESvsDtlUTT/KnoEYkPMVB9Iswe2cni/NAkkv4Eo5+xK1/qlD0uVEjrGL9+zTkPwP8FIDjMHgeQkB0eVw3HgAzH2fW5xJjJ1jDvHxf0w2D3LbKHL7141s76LTyqpd0EDPq0HcnWWM8NP2ncsZxJWy8PYFxkG/mgh+MwBtzo22i4OkJI5dxmdW4EKXVGUfFVHNf6FOUzvfbJIcr+91m/WUuxQK1HKmIxayj5D958hS8=
  template:
    metadata:
      creationTimestamp: null
      name: hopr-3
      namespace: production

