apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hopr-4
  namespace: production
spec:
  encryptedData:
    API_HOST: AgBKuzsQuU4qtpSi6lso2mlstbCiE5RECWSjfSp9fvaEVMMv6hhGekCZVa0U7tTex4Q3iZb647o/aNO/lp4by2WgMvuEihOEqM3EZVIDLAF7SMr6vUZBCPQ4t2VHINGwQ0xUEGyHxAF1SXKbzlLiUvwacAI501uTcozMyV+0Uh8VI0ud80x7L1NXKOOpqKFAFUB0Zq7CLmq4BAQKbRk22wwsVHR5Kjf/Aul1DfFKVSDV+fiO/9h8xyKf3ADuIP3v/WhMkAJUDMu3kdftuiji2JxPZsslUCgmkLsy4dx0jaBhrMoMrT4WFS8O0TfPicSUnhd/tWiwWvgluD+xoiTLea/fDqLTzfVLymy4Gm7okRwRubqM02D9wVetE7VvC5t702sRmwjLSG0ZoOZd43tQcKmWhUT0n73Oy7MnwI0WdHJhudTbWjVEJIypfeuleRGBJTVB2weLdx5J8BnIhtdKAiQhAIaabVSg3kgxacMtlrjXtqjYTFDM764vMsV7+akJtPNJaNuizcMEHYneSVoPY2XeTan8/fgPtTn1tpnYRtE7RYy0u84IHLLrJM+WBL7xkos/wSapyJgol/Dv2vp0WeKQVIDsEqS5HsieXr/vGJ5aoBzvggQVKV7dQ4Q1LF7bAnmUvCHRgtPzn7Bkvj1ZFK1a6OtopNk+9F5taEzK3BWp4yMr2WTcPtAMltg+VyYElZSfczdecjM0tmg7tnbHj6WKFVXoGmmZhA==
    API_KEY: AgAghMaA//zSs2LGAnFBaOzD5ObRs2ZEHAAqDqmUY+HAQjWl5Ju8Grt74j1Apy8c8mKDngjfir08DbcyuMQiTdhk32Dn4BbUrJjqRWFCV5prrZjPrSlY5sOHgxuIwC1PxVhmFHeNDuTxdOXffbie5hk7yGzFPKv2/PhhI1/aXzX66PTiR5qNvw/DuwPlU6tPy+K+O/KWT7lrsslMaWroherkjWnywpvcdIr42OQ2yZr9wlveayNutx7G10s+MheHl95oGjpjWteGmR3hjm4BKKETWPSJQbzQKWbNKP+PkXtgBkqpyDg7Z6UZL+9wIje/NrtfS7XmgCxlBYl02+WSGsPYLf313o/x2z6xurx2Ae2Cw4vf5f9u/Z2/Rzc2SESrfXJK5Zqhm3acbCskTSEiNPatKjvxptBYKWV5TNibqvNfHoBH/ogIx0PgIUC29LI+Nshp6WJkvOft2LUZQ3mtiJrBMGLsHXNuh5UWg7/Ia5Qdoym77DSXnh0GNFfDP1y+B+6kD4XD3B3L5GHGcB0xAkKMj5LKuGxU7QpF0cotupexkDshiiO8g3n+XYvQ7h9qJxUpSFPEAIZ+VVKLHPFcfNbtZ91VRuXH2gDuZ7rjCDPVTArHJzBPy5DsISea5m/bkJZSORuY/+MuaI4RlL4JRxYWUJmMdk/QARocA9TYrD18VTllU4YgG9t15FZl9JITylsTxutH9svnLP4SnOwxmNJwZ9rDGw9D0S17CnnlLuM=
  template:
    metadata:
      creationTimestamp: null
      name: hopr-4
      namespace: production

