apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-2
  namespace: production
spec:
  encryptedData:
    API_KEY: AgCfdaFxjQOPz2n4ddWXPO4sVeCU2VgLrXUbkmHV3eVzBvhXvKNWK/93Km8XAgP9EDDLT+4p8WWXF7l3lSdH+6g4VXDwiyYSPD6U89DTJtYzF91lwNhtqq4wENo/w6edLie6DNCREkFtb0yTa2CB8zmtp3KN2JvvnWBoVyUCzbpDpKH7JLrLYNJ/J7Eg9p+LG8XssXDRICbA3MrKCcJMMfquSAJ0BVe1K0Fjezy73O68Cnnhnyn09ic3EJ7rr1Vy+cy5exJc/j914QRpNnzJDHkKHmqRGtC1YSUwB9dEi0z8Evs/RuXrmSVNDEYKXYgmVmS6WrAJcVddkRdf8ZPhf/tBq/mNhImhW0nuuoAMhaVcHfu3CRXcEc60t589Ottztbhw2kw+dZ+c1AhIkJZlxBGsXEJzSux5l5/v4ypf1mRvrtIf3BwHlFtPRHdMxLz/XZiOvvwse04aNUreeCoGt1pcwwInGku6HX/J4vWQ+cos4AtU8/NomZiBDsp0bTKYA5y1VOEjuJC/77XXPAjdFbM17+cRr2riLXBbg1fG9/ip5NJSJyBgi5wkc2myN5E95+zZA1p99SXTZ6Dzbk+0yvQOKaEfZJL7HxxOmLNz3QtXebi4R5dc815GGGnKnhkumJ0R4wKG0Q3CIiJvaxQbpWhK77kNJ5Di+3QxFPMa85XZO8N31r0uGaoJO8rkq/B2IDlwpbA/C92RIz9meVSZh/qH5e2GqapNIgLPU1HzRgk=
    username: AgA4MAcPKVs15LL2Jq2iqeukp7uRDaw4akEnuXrvNFksyh8c+3Vay7WYxe7oahBSIAZP9gyWNSYKq98N9xjuS7/zIaxN88S+jomtMcE7OBpZyMUZljRvGZMSp/LhQgSCEMEnhDCDgO6x8JP+gYHtGP2khkkkMwyV17ovPA4nYR+ejs2zbxGxVr2esX6UVVXbNOB9ba/ImzlpwBP1vtddBER8nYZF6H1FTjf6pshVkrGOsia+QqPnOgKUJboZXjIqol/VonGMVIvREwObrDgcJryqcy4ufHDGBAMcmes9KGkBiS0P/wDhlHVTquB+sVpK0boUMMoUUZWymav4JbuKPBapuVt9M5WMl7LrayW/T5IllI8WA4riWqWTdRcD2DHBZZ3R+NZB8dGPd2xY+JkRyZDbajEaNbtiPh2tXXJlmnnh5IibwEII1M3tnfp+kooHJsnB6Qk5/OEdpg+pWRtIIjRXCkyyFgqpBFxe4Dag0HT8HAiUJgWVSwuB5Og4be5k5Xk+UTFkq9aPi/uQkWsS0eySaWySa7+zM/Ai0MKwF5Eg8BHJ4yh1j8uU2hiZozzuni6Y5AIlL4u6o4GlZ9Iu+rNQv1Zj0lpYZwiCdWU0vf+XI0EHTfU3SvLxqjIUjjnq/XiG7eWBy+E3p4pUwntGrJqMla4pKpXerGlMgGwiQAauD3G3u+Y+Lr/hsn0oJ7TvA8hc9sgK40ZSA+IBCuTh9b68JkEC5mcqfg==
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-2
      namespace: production

