apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-5
  namespace: production
spec:
  encryptedData:
    API_HOST: AgBaRI80YV9Lrh9IBVd7OfIaU926hrUy0MOTHnPV1VqqP4fCLa55hLnz0z3SjdFXi3YNAR9wQ0jzs/LJyGzcJgi//DeLR4U5nqEhK0yZroQV09fEanG2oMPfaY7Efh6iWMQkCfBUvAw2OD/rUI00tM4sERa6rrShzAuM4XZ5DFjG355gSuFgBUy59VQpdbtokRPvL3tYKLMkq/P7lju5+DKbiq4r/iTIpFmekJLtVx0x2PBAITCnfx5EK1qbVmOn/PxPjXkXPqWWpI4uap5CfUKL7XM/QIZCdzRM8Yunzd7StcbrxaoTTQgS6OogBYnlYiU7krxN17fT/1F2hLqUTLuHk5yrhyvN3gIcWWg+ayhNZpDARxtmPz4G5KByuMzzwBtIeFvfja/u77rtvecz/uUd0xCqzrYOhNujNXRoUXl0dD433LQfcAAOvMS+sNOZPuRCjBJYIojCONcUfCv3gzVC8A9hvGWuxRLgxIWsBt+iR2SOOo6OjHhK+Xd3u84hGx4CAYULv5Mg026LFlEeecgZuLLYGGq+xRcgyCqjqiji8wfF8WEjmf+xGdq0Lx0xvj7qCI6NLa6sa9bSOL1qUgp9aUbCI1FNWU1OsXX6RFJwA69XpmufjIRRkR0ErxesEXORMyVGBIC9WwEH01BrLYeYtJneLUHKziwCGg2z+wLC2PgtdzCJF3LtRn2x64DtczNrkOTF4nGaBfSs8cx4
    API_KEY: AgCcXxtg0A1o+4zRlPc+gurfTRWgC7Fq30cZNf7GVzDpgCh2A3Txt9y1/qDITDUfU/Ez3Zx81IALdxj0tXexKDdi+O4BKQL0NR8/GrSUATqe+U6L3qHF1NqshF0RPIb0HkE9Qg5JWiV3iS/OoynaSmXxvxFCfc7xnX1qYCDPypC3TFMLXBX9TbsMvoGx7hXc+OvB3le93lw4aWaqILWwZ7ZUnfrgT+niMQWbTpyZjejlxXjfJTB/0RFotbYZrQRqIdlqyZDjFNvcFizoFmDEIkg6JVDAz4ElHfCeJ49Oeoy3QkAy31os6dVpfsl0Jil+XXse/J4AlwksaVVt61Qp3EJOgDyKKH9KQ3jgd3bm+Dc0wU7a/9sXCwynUj7zS/mkjrJDMCAXMW4MyBApq7vtaUesX7pcOz+b3x6yPp12V9dykw+sFUyNlqkeh0QS/pkwcDs++TcI88QqvTyhhTTxAXKF+a+xUfwvWQ4cyv7g0VMFxEzdseYKP3wg6rbsQbIYkyiumz24N6T41V/LMo+zUtb6tJlQr3TDHvouRGHnn7AB2GvO+ccgOOtmvtJAdgbpS6ROk/Q7lt81AHZuYXP1TD4VeOukxlnFJiQuwwmqM6DCWgVVzCqbOTu9HvoBMdHf8YU0azD812YYejdzmXFu/pgGBWGpyPiBbjaklYwJ6Cj3F1x0ab+ysrgCUKxWDydfp470q7Hi65YE3wZfNH0rZC6SUthymTpYAsC+rdQsQ9A=
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-5
      namespace: production

