apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-1
  namespace: production
spec:
  encryptedData:
    API_KEY: AgAxysuv+Jt6G7fWGwqKzB/KGsunMp06hTcJLMbSTGztrJ/FticC9+CHiuzdOYHSIdonNJxcvFN9AbX9+XdDKodczKWLolDSHNMGqllVlJAnVoN/84rAdkIQwl5vl7ixW+vISkreSqWOgkUk04/jqtmmYryrqMJAea8L3QWH9dzG3RH0QGvbAXus5L5+ZrrDdsgTbsEw2tPCzFssiRTsW2twFAeoyy6Uro/LNMDKTLhRpySInsKOmDYkjFWbnpirHhMCR4KgWKdfhv760aBhlEhkxu3b9brC8XOvQNKBKzLpKhVGml397Bdr3NT3kq/ov4kKwRG1svy/Jd630xMmBRd31u3K2aHPkwuKxTOFnPcCN2ZVRYfENHucUwzuE+LpQKT+R6I3jd5YXy5nLy1fwEBh9OEsK2eaj85Td1V9lXafk7la+9cJ+thJyxPCVyiAAEUatPiusL+WLOOwmXytm0r/Ag5Lk19sxkzPxtxcm0DKksCEJXqCCTl2rlEPamA/brcEqDLgjsSREpBdER2Yf5fefaYqh7gVogLBhw4F40OzwM6JHPsdz63pXGuyT0Bs43s7BB0x1MuqIacTiJKlQWfjrKRQJFj3sBPujQQqfzeq/E9qQOfHNJcTOZBbiZ0g0/4c6ugHpStn/TATpRT4TmsezL0GsFTsBekMhwZ2VWMsYAfEwmGOGxRcSYFrp1/3qADkk6NBbyWi9G0GOdvRwYTgOHwfXf0B+AouUNP4lfw=
    username: AgBbm9jCgY+htBYeZ2WypuXmHOWysurbJSFn+IpWKdbQd69JXJSmsuGiMVAGa+oSOrX/y8i1S3nX3pnBUJz7jlR1drxpwoNRm5j1swxywKDWiQt//SXXoU+1VF3PUcWPHLuJtZuTlbXh57ue3IJVHs+I08pNl8d+fxyeH/QuwWHcnl90WRyTILfKBDsa3aAy9b5DJwyQ8tZYW/GvHO3dpb21VIVsxiU7UkwVwg9F/T3+l7fxI4z/qyXwayaDH5GuiiGI/wy9j6++xLtTAU/mVlglHVESVGypmi+muYlGw5TX1BbQvNc8OrI3QX8PMXOpUHRW6/k8JhIbu36muaYGEVNGCTZeXE8aNTVXjQzMFERoMRjN09N8DafeyNtqybsh7WnNk2PASx9R4ljfFSKkwJFUz+aGv/TWawI4Ep1GB7KPQoUptDBN+BU6nXZtTYZ0mwObmNxIkzxgI/pn74V6voELt6vhOteza97u8n8k9MJmFfkxBOmKNtdJDBktlNGdgH/cbPcnKLx57DHC82cCJXM3hIAL9yQ85cBnyxvZn2GD/ZbXTjvHwy4EGCTS4eLt5sU/FD6HluME6a+BbvEJ+3z5Dfa3HF5tp7cDcP7c+vH9mcxoQnoLs/PdEojA+KK94CbEzjdpVG2dhMOfHgvnoivSaBEwQ+X7r1az1d4Odc4qpMnbffylgM628enmQoyRR5UhKdZQCV/p6Awoj7pVvjoQjFdnes3a
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-1
      namespace: production

