apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-2
  namespace: production
spec:
  encryptedData:
    API_HOST: AgAjs9oza7yhzwZTvhCWBtXu1PxQNKLeGhUPhpLeapUhnQ8N9BCIbqO5izthp8dyzG7ZXjWeA8N2VOd6RkebX2/sULUMy9cJjVrrvT2guz3PtplSRegkXLcPDpqpq02PhNadC65QPHHTDDC3PtoqnvgGHJth16lSi2/WaLmFIvMXTL2BCz2BEwJi/yWSfIV16C5LwnIf73mEQU9KXrvH83B/TWYgbtdehxSgstwYfVeKWYhx1crW55KV2ErPiLJMaZX0MWLpeyYdq0+A9RnBtSLl8WLnQziVxzC/s0HNtvMcmSozwyYko1l1OMutHMK7Tb5Cbf4w6TisjADqFY7r81/0duK4KDE7LfIvMiPhJ4BW51LZEWRn1SnKqTFYuTKotnQszPYei7rabVI8FWfH5qzCPTxMbfjGdy+0GCmpmukMarXvS7X5Hw2b7jAXJSs1OIthcJA10/TUWL8Jzh2yN/4ovO0bJQtxK1BvRme0LGdDlWBr0kpqbN3xTU8ZVYyWoiFJzejgO6N3NjTB2549eSlIpVGe6eoOIf3c7q4m1ZABvBJI/3AClU3PMy+Son+yt0c6RrXyb/VZsdAobGFDtbD93SLC0KtHa/387l2JLySSgQo5bEeSE1wlZIjl4oHL/WY2hqW3j8t7h6rr3d7dG+KFWXx86qbc1LBD4lQ6CzDchCRLFuIzng8fLs57HOH5+v/i7d7g5RWz9lup40Mp1Q==
    API_KEY: AgCRT04tI47vVSxW+PlOWaRYp/0KgTmTY3h8uNiz49Q5o/GBrbGCmmUGDjZHKHxa8BSKEOAm5VMLyWWS6UDAsE0cBbwQNGdCYmE7xAke6IYzXHJzYFOUwSFOKdAcugkngZ4x6n2ywFzwYG/pAPnM7bkDyx3VJei5sw5j/FQHzz2S0dlkgQm7y5hlEhGfQDONiArEGW8BfU2kbepn/5vxiA2Cx5WT8IkW4fUw3YbPkj1vN4QjOAEYX7oHk+V4qDsXpBjfR2B6yHOiDgk0VaNumeaWPOpUXCvamFiUY8x237ILGqMLyguXG4VzPFvfXM2sNNOHGw0zSMm0Q1sgGhO+mS4UJqrKmy2gTSfZJps5cNZCxV1fwdZnoscnON1LsX/p/irJcFeFNrrwlJUmhPI1uqR5yFh9LxpPgaI9qRyCOh3/ccSlYwkIQgF51nfhq4jhHL2iSMpPID+O6fsrJoVBWfq5+7IFcrzwvZ219+Eq4yJe1os2M9RuI6/cot2r96uufeXgGNMUZAmCV7Q00Q9SprpLX2il6CtvHDHaxIl0IPiFfj78vgZ0sHugU/lfT7t7XlND9UeA6t5AhBOOrk4eDFo+D7GiG0uOdAg7R/nWR7zVvpBMMDwomBGtHKTBeFpSqFSo5+p1E1QZGI0mLVzkovgst+yOy8xdG5yXcXL0ecLGCqbtMyjoYmk3lQiwkztxjb2lGv/6OeTsoWuimIp72I+44hWPD/9yEnPzh4+JKCI=
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-2
      namespace: production

