apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-5
  namespace: production
spec:
  encryptedData:
    API_KEY: AgAeYIdxJIOmVRDoFiM1au/Q+eYbczhc0s3uMyZdmZf6AvP4+u8qKoC5joym0Qg7RHRhaKz1jEEO5jfnmlEsLraOhQ6RDGaC0Bqmw519kAKArQ8wz+ycPwj8T1dFCp5zNz/XvbqyZ00E4b67Qe5rzP2r+CDyxAthqVltyYbH6gS4btW0SbensF1oPXr11khIrylebgTstr1hH6Da4KG59w1zcygnLHeZ4a8x/2MolNW9u9aN/fogg72qHsls1ae+8BsZZ++FE4P3fSVpRR+XJsUSUvOuCtRSbjsBulHnvvptvEg7K7MjVx3qBBlIFlzhRiHDdnOzwYiLzZssZl/N6/0iz4YMNwWaQOdmxCJRW2pwXLqw1yfQ5XWM//dSLV4IPpNskW2v5hFzwHXJeWgHyXdGgzAF8caosg4tPXul6aS/dfmz66xlvb95III1UL7+pRREaYej7V1cRIevzvarJxodmkAz5zQCkAyqsnWtgJuu7NoKSfqij49GE9FFC/4MwPlsX4/acpi833Js5JEcL4EWMuZEdlPSVVNn+Ex5jH+lUycym4UoclCijRjZtnXLAM/svRDzc1pxveMQ5DPLhzV64NW3tZd3pKWV9YZtzZpt47wFNFymnc9jiU0MVx2ubauw0F/8ac4L/WxEcpCTBGPVQmj7hwF+qPm16njFyYhkNkdPmxTkDDJ+TLAhgqixwaGyKu0KrJGkktMoihsAQmTUG6+UsJHwfiu9/KH8lMY=
    username: AgAzKwnFgCmo5d/CLm5gk8ryRrjhgMOChcr0hHoS0oXNWBui7w3+MoLtYENua+E9IygxsqJj+2q4hb2kMzKU66mbcX9sfX0KPBDog9e8BwCAj7H69EmPq6ZySJCWFp8R134qAMc0m06P9ilrYcPsqx2YvC0MYr+cMWTikwcYr78sbd/FZ7XMNahtdJFdjaFLCXxKkaY2k+0m/14PzShvTYOwAzLYyJOLRo8dPB2xdKSs3s/2JHSDmeLEIn7dVTKzXo9SmiF3Zd0qqlQxjW4f+s2f0I0GzD12bIkgC4zeWuixBPoe6okCQHc+onZSjw55iUhU34SB3TozHHUDqkNLSxlrY9ucHM7SkNbrhOac5K6sBvdnfxQMMnXbd1KnMOgGKFcDl5572FtntBphzcs9h6OlptaTxTTYq0ROSMN7Pr9+nzi46GoClnTHYFht9taQLpOX1zUmydFK38MbiDdi0YCaOpZbf7gNvSUe7YIkL8H4z+cuBC2ybZ1Ar3y4C/ZJjdf8e2YetU3qv+fjEY0wTRLSJrBhrpgvPiac5KcJ0+ZcKHnkqeZe8pARlcE9swx0IbnlZ0K882JFEYkOfX8gJn/tPN2Nh9HDhh8e8EWqChi1RMn5dSkzKyIr4DsL2mMVnUM5L0iat4vXEt3D0gtup+etxMJylTKsyyv8fs/TZQdxalnpPr6XIk0EvzBsPdctz/wyaad9eEfRzlYvyty47vICW6soQXoN
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-5
      namespace: production

