apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hoprd-2
  namespace: production
spec:
  encryptedData:
    API_HOST: AgBB0nDIXwnwcJ7dIeClTlv/bt8phWMBXSYME+6PH0d5l40aRVOrzu9YYEYBeavDF2X19FGNXq/Za/TK49LI11j/rHhO55reClTFpRkbfrEyy/FzFd1SCbiWg4IQtikr6/UKJv/6kmhymLOmnmO3+TseMkm+eZhDMvTe8etmUBYtPjz4hx/ZnB8Ax0UI2q8QfpgtPDy7N2TCqSri5U/xxV0jaJo+iFPQfwF8drDJYCxQOf9SaunLMsrVwfFALLhl7OJtYr1KlaYMVRq1IvEcRD65qIhljUZHcKLaJcWOEzXSh22NVyM9aMk0UWV5QjpDr00OWgiXMf898BwRKgDJSXqrxkIzcjy9o3iYbVqJ04AghIL4IJxEvwlKEqcW8KslxrJuiJDwPL0WX6VbHsvSDYYvAa5DaOMg4EJg6dJdEkJWMAxnSMi+z5y6QIFHgZnnjuLC9FCa8rBne6le+5j0xkc4RghvnNI/nqcvBkI3mlwR2gjf8zkDP3el1DOXeQY2hjJGZxoXDnMEKCsZQwROuCFVEcjJSRB71umYhpTsl8HLAyb8/5Yh/UcvEgZmr4wDuS2f+WJT9IQMLh5ZMFf6YqXunlrPM74ZigHuv4RDrb4S73t60Iq/Ziy2o0L0dAjn0cyPjtpKTxXMwB6T9KCJqTx1L+3dUugTglIytqp0dcLvg6JkyvF7pu7Mmwozu9WkgVlAw0mHybSbjkHRnkIdp6Ug5uKNaOkCwy4=
    API_KEY: AgCPN2AISKms+C9IX3ndAK1AXxzFoq/+0l1/z/qT07BjKVeaeIkeoeunwYqEYekaqccAlD3ULTyLQiy+vucwhBd82SfMK+RWIHj+Fjdp+GK9Zovi//gEF3rinh8K4JsuAn4U5N+RjAJjcmovTVMC9++PuN4zBLbSR6O9buzs7ozgjeTs7uhPWPD0ChrFKhp0bmd/RotWfSh9q7gOu2kI5m+ETachiIi6lqxdEjBwNsI9LcmsfwgSn/4NvSlf1ZFiCy+uZ/kMkqDFr0injNDNxZJ5v+J3HWDpZ6zL42LI+PBk1PNYAGWw/xatQLLqL/wo+7xEW/OCEJYxMNJeXMEXtFb+TDLfQG8P+XZHDLzhvvnnk+3jzxilulriFEKqHRZVq1/J/lApRHYZK60B1OlFIkjSReslT5ICy5vv+3uFjXJGoyZPNGhUzRLsVHNdsu5PqvWmc0ZnPuose3vFN9528pOSn0wgbdgDbqXZwGGWcBSy7B2PHe0alFWuxIkFMk2yxc6wbHlm0n/BbZIOeh0hdxzFdD7MwNYf/DkJ8qkPmqFt30IoogYVxfT1xxaiPE/r/u8BtaNU6qf40oVG2GHIVvMacMTLxmnY9yPchEYu8zzhXrZCXXml6OfdGePR2S5kFhQjZ1e7K1sRUoSeBM0zTOkRKBGG6OxOdSEiL3OyGrAlG0M3Juv2pTUoZq6KRkD2QkVHqRbwBSnW/L6LrYmXTKGTnS2NBDztK672wsocD3g=
  template:
    metadata:
      creationTimestamp: null
      name: hoprd-2
      namespace: production

