apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netwatcher-4
  namespace: production
spec:
  project: production
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    helm:
      values: |
        app:
          name: netwatcher-4
        image:
          repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
          tag: "119d15f"
        replicaCount: 0
        args:
          - python
          - '-m'
          - netwatcher
        env:
          AGG_POST: http://aggregator.production:8080/aggregator/peers
          AGG_BALANCE: http://aggregator.production:8080/aggregator/balances
          LAT_COUNT: '50'
          MOCK_LATENCY: '1'
          CHANNEL_INITIAL_BALANCE: "60000000000000000000"
          MINIMUM_BALANCE_IN_CHANNEL: "15"
        envFrom:
          - secretRef:
              name: hoprd-4
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      
