apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netwatcher-2
  namespace: production
spec:
  project: production
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    helm:
      values: |
        app:
          name: netwatcher-2
        image:
          repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
          tag: "ca68a7f"
        replicaCount: 1
        args:
          - python
          - '-m'
          - netwatcher
        env:
          AGG_POST: http://aggregator.production:8080/aggregator/peers
          AGG_BALANCE: http://aggregator.production:8080/aggregator/balances
          LAT_COUNT: 5
          MOCK_MODE: '0'
          MOCK_LATENCY: '1'
        envFrom:
          - secretRef:
              name: hopr-2
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

