apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netwatcher
  namespace: staging
spec:
  project: staging
  source:
    repoURL: https://dysnix.github.io/charts
    targetRevision: 0.99.16
    chart: app
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            image:
              repository: europe-west6-docker.pkg.dev/ctdapp-391309/ctdapp/cover-traffic
              tag: "ca0bb4c"
            replicaCount: 1
            args:
              - python
              - -m
              - netwatcher
            env:
              AGG_POST: http://staging-aggregator.staging:8080/aggregator/list
              API_HOST: <random_host>
              API_KEY: <random_key>
              LAT_COUNT: 10
              MOCK_MODE: True
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
